* Vocabulary

** counterparts [ˈkaʊntərˌpɑrt]
n. 【法】(正副两份中的)一份；骑缝图章的一半；相对物；变体 | 网络 同行；副本；同行新闻

** noninflammatory 
un. 非炎性的 | 网络 非炎症性；非发炎性；无炎的

** rephrase [ˌriˈfreɪz]
v. 换个说法说 | 网络 重新措辞；改述；改用别的话表示

** unleashes [ʌnˈliʃ]
v. 〈比喻〉解放；放纵；发动；解开…的皮带[链索] | 网络 释放；发泄；松开

** spindle [ˈspɪnd(ə)l]
n. 轴；纺锤；心轴；指轴 | v. 长成细长茎；长(变)得细长；装锭子于 | adj. 像锭子的；母方的 | 网络 主轴；纺锤体；纱锭

** manuscript [ˈmænjəˌskrɪpt]
n. 手稿；原稿；（印刷术发明以前书籍或文献的）手写本 | adj. 手抄的 | 网络 底稿；手抄本；文稿

**  tall order 
n. 难办到的事；苛求 | 网络 离谱的要求；难以完成的任务；苛刻的要求

** heuristics [hjuˈrɪstɪks]
n. 探索法；启发式 | 网络 启发法；试探法；启发式方法

** manicured [ˈmænɪˌkJʊrd]
adj. 精心护理的；修剪整齐的；护理得很好的 | v. “manicure”的过去分词和过去式 | 网络 修剪过的；修过指甲一样；整修的
** accommodate [əˈkɑməˌdeɪt]
v. 容纳；顺应；提供住宿（或膳宿、座位等）；提供空间 | 网络 适应；调节；供应
** destructive [dɪˈstrʌktɪv]
adj. 破坏性的；极其危险的 | 网络 破坏的；毁灭性的；毁灭的
** obsolete [ˌɑbsəˈlit]
adj. 淘汰的；废弃的；过时的 | n. 废词；被废弃的事物 | 网络 已废弃的；陈旧的；作废的
** hassle [ˈhæs(ə)l]
n. 麻烦；困难；分歧；争论 | v. 麻烦 | 网络 激战；激烈争论；争辩
** beforehand [bɪˈfɔrˌhænd]
adv. 预先；事先 | 网络 提前；事前；事先地
** paramount [ˈperəˌmaʊnt]
n. 最高；有最高权力的人；元首；首长 | adj. 至为重要的；首要的；至高无上的；至尊的 | 网络 派拉蒙；派拉蒙公司；派拉蒙影业
** crop up [旺旺英语论坛]
v. 突然发生；出现 | 网络 突然出现；出其不意；突然发生或出现
** TRAMP [træmp]
n. 流浪汉；流浪乞丐；沉重的脚步声；长途步行 | v. 踩 | 网络 流浪者；不定期船；践踏
** transformational [ˌtrænsfə'meɪʃənl]
adj. 【语】转换(生成)的；【数】变换的；变形的 | 网络 转换性；变革型；转换型
** impaired [ɪmˈperd]
adj. 受损的；损坏的；出毛病的；有（身体或智力）缺陷的 | v. “impair”的过去式和过去分词 | 网络 障碍；受损害的；削弱的
** key stroke 
un. 键击打；键触击 | 网络 击键；键深；按键
** deter [dɪˈtɜr]
v. 阻止；制止；威慑；使不敢 | 网络 吓住；妨碍；防止
** manifold [ˈmænɪˌfoʊld]
n. 管汇；汇集；复写本；【机械工程】歧管 | adj. 许多的；多样的；由许多部分形成的；繁茂的 | v. 复印 | 网络 流形；多方面的；多支管