;;; Automatically generated by ‘recentf’ on Sat Jun 22 16:15:31 2024.

(setq recentf-list
      '(
        "~/Documents/BookBase/Mastring.Regular.Expression/01.mastering.regular.expressions.v0.org"
        "~/.emacs.d/customizations/ui.el"
        "~/.emacs.d/customizations/editing.el"
        "~/.emacs.d/customizations/init-org.el"
        "~/.emacs.d/var/bing-dict/vocabulary.org"
        "~/.emacs.d/customizations/navigation.el"
        "~/.emacs.d/init.el"
        "~/.emacs.d/ido.last"
        "~/.doom.d/config.el"
        "~/Documents/emacs-bing_vocabulary.org"
        "~/.emacs.d/elpa/bing-dict-20200216.110/bing-dict-autoloads.el"
        "~/.emacs.d/elpa/bing-dict-20200216.110/bing-dict-pkg.el"
        "~/.emacs.d/elpa/bing-dict-20200216.110/bing-dict.el"
        "~/Calibre Library/Unknown/01.mastering.emacs.v0 (3)/01.mastering.emacs.v0 - Unknown.org"
        "~/Downloads/emacs-for-clojure-book1/init.el"
        "~/.emacs.d 2/init.el"
        "~/emacs-distro/doom-emacs.d/.local/straight/repos/themes/doom-themes.el"
        "~/emacs-distro/doom-emacs.d/.local/straight/repos/themes/themes/doom-ayu-light-theme.el"
        "~/emacs-distro/doom-emacs.d/lisp/lib/themes.el"
        "~/.emacs.d/customizations/misc.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
