;;; Automatically generated by ‘recentf’ on Fri May 10 12:15:29 2024.

(setq recentf-list
      '(
        "~/.emacs.d/init.el"
        "~/.emacs.d/customizations/ui.el"
        "~/.emacs.d/ido.last"
        "~/.emacs.d/customizations/navigation.el"
        "~/.emacs.d/customizations/editing.el"
        "d:/02_data_dumping/zookeeper/znode-export-2024-04-16T09_21_42.765Z"
        "d:/downloads/znode-export-2024-04-16T02_06_36.838Z"
        "d:/downloads/gi-app-0_gi-app-container (1).log"
        "d:/downloads/policy-generic-app-0_policy-generic-app-container.log"
        "~/.emacs.d/var/books/Mastering.Emacs/01.mastering.emacs.v0.org"
        "d:/04_program_file/MSYS2/mingw64/share/emacs/29.1/etc/DISTRIB"
        "d:/04_program_file/MSYS2/mingw64/share/emacs/29.1/lisp/custom.el"
        "~/iCloudDrive/Documents/Mastering.Emacs/01.mastering.emacs.v0.org"
        "~/.doom.d/config.el"
        "~/.emacs.d/customizations/init-org.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
