;;; Automatically generated by ‘recentf’ on Sat May 18 21:52:27 2024.

(setq recentf-list
      '(
        "~/.emacs.d/customizations/init-org.el"
        "~/.emacs.d/init.el"
        "~/http:/xahlee.info/emacs/emacs/i/emacs_list-colors-display_2021-07-19.png"
        "~/Pictures/photo_2023-09-09_04-47-57.jpg"
        "~/.emacs.d/var/books/Mastering.Emacs/ /Users/dingyu/Pictures/photo_2023-09-09_04-47-57.jpg"
        "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/井井有条/attachments/Pasted image 20240128102807.png"
        "~/Library/Mobile/Documents/iCloud~md~obsidian/Documents/井井有条/attachments/20240128102807.png"
        "~/.emacs.d/customizations/editing.el"
        "~/.emacs.d/customizations/ui.el"
        "~/.emacs.d/var/books/Mastering.Emacs/01.mastering.emacs.v0.org"
        "~/Downloads/攻殼機動隊Ghost in the Shell (1995) Movie.en.ass"
        "~/.emacs.d/customizations/misc.el"
        "~/.emacs.d/customizations/navigation.el"
        "~/.emacs.d/var/bing-dict/vocabulary.org"
        "/opt/homebrew/Cellar/emacs-plus@29/29.1/share/emacs/29.1/etc/DISTRIB"
        "~/.emacs.d/ido.last"
        "~/Documents/Mastering.Emacs/01.mastering.emacs.v0.org"
        "~/.doom.d/config.el"
        "~/Documents/emacs-bing_vocabulary.org"
        "~/.emacs.d/elpa/bing-dict-20200216.110/bing-dict-autoloads.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
