;;; -*- coding: utf-8; mode: lisp-data -*-
(("/usr/share/emacs/29.4/lisp/emacs-lisp/timer.el.gz" . 9410)
 ("/home/madcomet/.emacs.d/elpa/immersive-translate-20231001.1557/immersive-translate.el" . 25003)
 ("/home/madcomet/Dropbox/vocabulary.org" . 234)
 ("/home/madcomet/.emacs.d/customizations/navigation.el" . 4234)
 ("/home/madcomet/.emacs.d/customizations/init-org.el" . 2355)
 ("/home/madcomet/Dropbox/org/04.metalinguistic_abstraction.org" . 9272)
 ("/home/madcomet/.emacs.d/customizations/init-java.el" . 141)
 ("/home/madcomet/.emacs.d/customizations/ui.el" . 3387)
 ("/home/madcomet/.emacs.d/init.el" . 2043)
 ("/usr/share/emacs/29.4/lisp/progmodes/eglot.el.gz" . 76347)
 ("/usr/share/emacs/29.4/lisp/files.el.gz" . 59700)
 ("/home/madcomet/.emacs.d/customizations/init-eglot.el" . 1324)
 ("/home/madcomet/.emacs.d/customizations/tools.org" . 1569)
 ("/home/madcomet/codebase/src/spring-reactive-sample/vanilla/src/main/java/com/example/demo/Post.java" . 533)
 ("/home/madcomet/.config/kmonad/+keytron.kbd" . 676)
 ("/home/madcomet/.emacs.d/customizations/tools.el" . 610)
 ("/home/madcomet/.emacs.d/customizations/init-treesitter.el" . 1240)
 ("/home/madcomet/.emacs.d/customizations/editing.el" . 7252)
 ("/home/madcomet/Dropbox/Mastring.Regular.Expression/01.mastering.regular.expressions.v0.org" . 12764)
 ("/home/madcomet/.emacs.d/site-lisp/emacs-application-framework/eaf.el" . 40263)
 ("/usr/share/emacs/29.4/lisp/net/dbus.el.gz" . 10685)
 ("/home/madcomet/.emacs.d/elpa/doom-20180301.2308/doom.el" . 2246)
 ("/home/madcomet/.emacs.d/elpa/command-log-mode-20160413.447/command-log-mode.el" . 1745)
 ("/home/madcomet/.emacs.d/elpa-29.4/dash-20240510.1327/dash.el" . 1356)
 ("/home/madcomet/.emacs.d/elpa/dash-20180903.1042/dash.el" . 21417)
 ("/home/madcomet/.emacs.d/elpa/dash-20240103.1301/dash.el" . 1291)
 ("/home/madcomet/.emacs.d/elpa/kv-20140108.1534/kv.el" . 1138)
 ("/home/madcomet/.emacs.d/elpa/queue-0.2/queue.el" . 1974)
 ("/home/madcomet/.emacs.d/elpa/restclient-20231010.1327/restclient.el" . 713)
 ("/home/madcomet/.emacs.d/elpa/org-contrib-0.6/org-choose.el" . 2416)
 ("/home/madcomet/.emacs.d/elpa/spinner-1.7.3/spinner.el" . 4238)
 ("/home/madcomet/exercism/emacs-lisp/acronym/acronym.el" . 201)
 ("/home/madcomet/.emacs.d/elpa/vc-use-package/vc-use-package.el" . 1405)
 ("/home/madcomet/.emacs.d/elpa/spinner-1.7.3/"
  (dired-filename . "/home/madcomet/.emacs.d/elpa/spinner-1.7.3/spinner-autoloads.el"))
 ("/home/madcomet/.emacs.d/customizations/init-minibuffer-completion.el" . 1783)
 ("/home/madcomet/.emacs.d/elpa/eglot-java-20240501.922/eglot-java.el" . 7038)
 ("/home/madcomet/Dropbox/Mastring.Regular.Expression/Mastering.Regular.expressions.epub" . 1382)
 ("/home/madcomet/tmp/ejc-sql/ejc-sql-editor.sql" . 48)
 ("/home/madcomet/.emacs.d/customizations/misc.el" . 955)
 ("/home/madcomet/codebase/src/spring-reactive-sample/boot-reactor-kafka/sender/src/main/java/com/example/demo/SenderApplication.java" . 2187)
 ("/home/madcomet/codebase/blog-bus/dingtele.github.io/archetypes/default.md" . 269)
 ("/home/madcomet/codebase/blog-bus/dingtele.github.io/content/post/pinned-post.md" . 1094)
 ("/home/madcomet/codebase/blog-bus/dingtele.github.io/content/posts/my-first-post.md" . 144)
 ("/home/madcomet/codebase/blog-bus/dingtele.github.io/themes/terminal/assets/js/prism.js" . 38885)
 ("/home/madcomet/codebase/blog-bus/dingtele.github.io/themes/terminal/assets/js/menu.js" . 1111)
 ("/home/madcomet/codebase/blog-bus/dingtele.github.io/themes/terminal/package.json" . 725)
 ("/home/madcomet/codebase/blog-bus/dingtele.github.io/themes/terminal/package.hugo.json" . 3)
 ("/home/madcomet/codebase/blog-bus/dingtele.github.io/themes/terminal/README.md" . 129)
 ("/home/madcomet/codebase/blog-bus/dingtele.github.io/hugo.toml" . 2990)
 ("/home/madcomet/codebase/blog-bus/dingtele.github.io/themes/terminal/static/terminal.css" . 292)
 ("/home/madcomet/codebase/src/ejc-sql/README.md" . 3516)
 ("/home/madcomet/.emacs.d/var/treemacs/persist.org" . 56)
 ("/home/madcomet/.emacs.d/customizations/init-elpa.el" . 527)
 ("/home/madcomet/.emacs.d/elpa/embark-consult-20240919.1831/"
  (dired-filename . "/home/madcomet/.emacs.d/elpa/embark-consult-20240919.1831/embark-consult.el"))
 ("/home/madcomet/.emacs.d/elpa/embark-consult-20240919.1831/embark-consult.el" . 1823)
 ("/home/madcomet/.emacs.d/customizations/init-core-overriding.el" . 488)
 ("/home/madcomet/.emacs.d/elpa/transient-20240321.2209/transient.el" . 3389)
 ("/home/madcomet/.emacs.d/elpa/embark-20241003.1953/embark.el" . 177311)
 ("/home/madcomet/.emacs.d/elpa/org-zettel-ref-mode/org-zettel-ref-core.el" . 13449)
 ("/home/madcomet/Dropbox/book-notes/20241023T180251--test-file__overview.org" . 6749)
 ("/home/madcomet/Dropbox/book-notes/20241023T180528--vocabulary__overview.org" . 103)
 ("/home/madcomet/Dropbox/Mastring.Regular.Expression/test-note.org" . 49)
 ("/home/madcomet/codebase/+project/src/example/main.clj" . 62)
 ("/home/madcomet/codebase/+project/deps.edn" . 66)
 ("/home/madcomet/.emacs.d/customizations/"
  (dired-filename . "/home/madcomet/.emacs.d/customizations/init-minibuffer-completion.el"))
 ("/home/madcomet/.emacs.d/var/url/cookies.el" . 485)
 ("/home/madcomet/.authinfo" . 83)
 ("/home/madcomet/codebase/eis_dir/edt/README.md" . 782)
 ("/home/madcomet/codebase/eis_dir/edt/CODE_OF_CONDUCT.md" . 660)
 ("/home/madcomet/.local/share/fcitx5/rime/moran.schema.yaml" . 813)
 ("/home/madcomet/Dropbox/Mastring.Regular.Expression/"
  (dired-filename . "/home/madcomet/Dropbox/Mastring.Regular.Expression/Mastering.Regular.Expressions.pdf"))
 ("/home/madcomet/"
  (dired-filename . "/home/madcomet/.emacs.d"))
 ("/home/madcomet/.emacs.d/"
  (dired-filename . "/home/madcomet/.emacs.d/customizations"))
 ("/home/madcomet/.emacs.d/customizations/init-lsp.el" . 441)
 ("/home/madcomet/emacs-distros/java_emacs/emacs-configuration.org" . 10904)
 ("/home/madcomet/emacs-distros/java_emacs/emacs-configuration.el" . 5601)
 ("/etc/udev/rules.d/00-kmonad.rules" . 47)
 ("/home/madcomet/.emacs.d/elpa/bing-dict-20200216.110/bing-dict.el" . 9243)
 ("/home/madcomet/.config/kmonad/+hhkb.kbd" . 398)
 ("/home/madcomet/.emacs.d/var/desktop/.emacs.desktop" . 469)
 ("/home/madcomet/.emacs.d/site-lisp/desktop-recover.el" . 1989)
 ("/home/madcomet/Downloads/terminal.css" . 191)
 ("/home/madcomet/.local/share/fcitx5/rime/moran.yaml" . 5679)
 ("/home/madcomet/.local/share/fcitx5/rime/default.yaml" . 299)
 ("/home/madcomet/Dropbox/Mastring.Regular.Expression/Mastering.Regular.Expressions.pdf" . 287)
 ("/etc/udev/rules.d/00-hhkb.rules" . 63)
 ("/usr/share/emacs/29.4/lisp/loaddefs.el.gz" . 408269)
 ("/home/madcomet/exercism/emacs-lisp/acronym/README.md" . 196)
 ("/home/madcomet/exercism/emacs-lisp/acronym/HELP.md" . 742)
 ("/home/madcomet/.config/starship.toml" . 443)
 ("/home/madcomet/.local/share/applications/Follow.desktop" . 118)
 ("/home/madcomet/.cache/gnome-software/odrs/ratings.json" . 949480)
 ("/usr/share/emacs/29.4/lisp/custom.el.gz" . 52851)
 ("/usr/share/applications/emacs.desktop" . 416)
 ("/home/madcomet/.config/" . 119)
 ("/var/spool/lpd/" . 108)
 ("/"
  (dired-filename . "/afs"))
 ("/usr/share/emacs/29.4/lisp/desktop.el.gz" . 49194)
 ("/home/madcomet/Downloads/"
  (dired-filename . "/home/madcomet/Downloads/dropbox.py"))
 ("/usr/share/emacs/29.4/lisp/tab-line.el.gz" . 4613)
 ("/home/madcomet/.emacs.d/var/" . 1677)
 ("/home/madcomet/.emacs.d/var/bing-dict/"
  (dired-filename . "/home/madcomet/.emacs.d/var/bing-dict/vocabulary.org"))
 ("/home/madcomet/.emacs.d/customizations/init-site-lisp.el" . 867)
 ("/home/madcomet/.emacs.d/desktop-recover-tmp/◀[Emacs_CN Lite 轻聊版]" . 2044)
 ("/home/madcomet/.emacs.d/site-lisp/" . 628)
 ("/usr/share/emacs/29.4/lisp/register.el.gz" . 8261)
 ("/home/madcomet/.emacs.d/var/auto-save/sessions/"
  (dired-filename . "/home/madcomet/.emacs.d/var/auto-save/sessions/1067754-fedora~"))
 ("/home/madcomet/.emacs.d/var/auto-save/"
  (dired-filename . "/home/madcomet/.emacs.d/var/auto-save/sessions"))
 ("/home/madcomet/.emacs.d/var/books/"
  (dired-filename . "/home/madcomet/.emacs.d/var/books/Mastering.Emacs"))
 ("/home/madcomet/.emacs.d/etc/"
  (dired-filename . "/home/madcomet/.emacs.d/etc/gnus"))
 ("/usr/share/emacs/29.4/lisp/international/mule.el.gz" . 10657)
 ("/etc/fstab" . 727)
 ("/home/madcomet/.emacs.d/var/books/Mastering.Emacs/01.mastering.emacs.v0.org" . 833)
 ("/home/madcomet/.emacs.d/elpa/"
  (dired-filename . "/home/madcomet/.emacs.d/elpa/bing-dict-20200216.110"))
 ("/home/madcomet/.emacs.d/elpa/bing-dict-20200216.110/"
  (dired-filename . "/home/madcomet/.emacs.d/elpa/bing-dict-20200216.110/bing-dict.el")))
