;;; -*- coding: utf-8; mode: lisp-data -*-
(("/Users/dingyu/.emacs.d/var/bing-dict/vocabulary.org" . 724)
 ("/Users/dingyu/.emacs.d/customizations/init-org.el" . 3572)
 ("/Users/dingyu/.emacs.d/customizations/editing.el" . 3028)
 ("/Users/dingyu/.emacs.d/customizations/ui.el" . 1899)
 ("/Users/dingyu/Documents/BookBase/Mastring.Regular.Expression/01.mastering.regular.expressions.v0.org" . 30465)
 ("/Users/dingyu/.emacs.d/customizations/navigation.el" . 4485)
 ("/Users/dingyu/Documents/BookBase/Mastring.Regular.Expression/"
  (dired-filename . "/Users/dingyu/Documents/BookBase/Mastring.Regular.Expression/01.mastering.regular.expressions.v0.org"))
 ("/Users/dingyu/.emacs.d/customizations/misc.el" . 1540)
 ("/Users/dingyu/.emacs.d/init.el" . 4417)
 ("/Users/dingyu/Documents/BookBase/Mastering.Emacs/01.mastering.emacs.v0.org" . 110742)
 ("/Users/dingyu/emacs-distro/doom-emacs.d/early-init.el" . 246)
 ("/Users/dingyu/Downloads/mli/all_up.sh" . 535)
 ("/Users/dingyu/Downloads/Telegram Desktop/Mastring.Regular.Expression/01.mastering.regular.expressions.v0.org" . 4316)
 ("/Users/dingyu/Documents/scip-practice.scm" . 3)
 ("/Users/dingyu/Downloads/Telegram Desktop/00.金瓶梅.崇祯本.org" . 83640)
 ("/opt/homebrew/Cellar/emacs-plus@29/29.1/share/emacs/29.1/etc/DISTRIB" . 20)
 ("/Users/dingyu/Downloads/mli/docker-compose.yml" . 252)
 ("/Users/dingyu/.emacs.d/var/linux-preinstall.sh" . 292)
 ("/Users/dingyu/Documents/BookBase/Reactive Programming with RxJava Crea... (Z-Library).epub" . 25416)
 ("/Users/dingyu/Downloads/Telegram Desktop/Mastering.Emacs 3/01.mastering.emacs.v0.org" . 129801)
 ("/Users/dingyu/.emacs.d/var/books/Mastering.Emacs/01.mastering.emacs.v0.org" . 1190)
 ("/Users/dingyu/.emacs.d/customizations/"
  (dired-filename . "/Users/dingyu/.emacs.d/customizations/misc.el"))
 ("/Users/dingyu/Downloads/mli/.env" . 1844)
 ("/Users/dingyu/org/notes.org" . 80)
 ("/opt/homebrew/Cellar/emacs-plus@29/29.1/share/emacs/29.1/lisp/custom.el" . 52851)
 ("/Users/dingyu/.emacs.d/var/books/Mastering.Emacs/Mastering.Emacs.epub" . 6845)
 ("/Users/dingyu/codeBase/leetcode-everyday/archive/202405/"
  (dired-filename . "/Users/dingyu/codeBase/leetcode-everyday/archive/202405/20240531_1573"))
 ("/Users/dingyu/codeBase/leetcode-everyday/archive/202405/20240531_1573/"
  (dired-filename . "/Users/dingyu/codeBase/leetcode-everyday/archive/202405/20240531_1573/README.md"))
 ("/Users/dingyu/codeBase/leetcode-everyday/archive/202405/20240531_1573/README.md" . 156)
 ("/Users/dingyu/Documents/BookBase/Mastering.Emacs/Mastering.Emacs.epub" . 6338)
 ("/Users/dingyu/Pictures/photo_2023-09-09_04-47-57.jpg" . 31993)
 ("/Users/dingyu/.emacs.d/elpa/ivy-20240214.2118/ivy.el" . 13793)
 ("/Users/dingyu/Calibre Library/Unknown/01.mastering.emacs.v0 (3)/01.mastering.emacs.v0 - Unknown.org" . 124815)
 ("/Users/dingyu/Calibre Library/Mickey Petersen/Mastering Emacs (2)/Mastering Emacs - Mickey Petersen.epub" . 2661)
 ("/Users/dingyu/.emacs.d/var/books/"
  (dired-filename . "/Users/dingyu/.emacs.d/var/books/Mastering.Emacs"))
 ("/opt/homebrew/Cellar/emacs-plus@29/29.1/share/emacs/29.1/lisp/progmodes/elisp-mode.el" . 55325)
 ("/Users/dingyu/.emacs.d/customizations/elisp-editing.el" . 240)
 ("/Users/dingyu/.emacs.d/customizations/setup-clojure.el" . 335)
 ("/Users/dingyu/.emacs.d/var/bing-dict/"
  (dired-filename . "/Users/dingyu/.emacs.d/var/bing-dict/vocabulary.org"))
 ("/Users/dingyu/.emacs.d/"
  (dired-filename . "/Users/dingyu/.emacs.d/.DS_Store"))
 ("/Users/dingyu/.emacs.d/.git/"
  (dired-filename . "/Users/dingyu/.emacs.d/.git/COMMIT_EDITMSG"))
 ("/Users/dingyu/.m2/settings.xml" . 1281))
