(require 'lib-eglot)
  :hook ((python-mode . eglot-ensure)
         (java-ts-mode . eglot-ensure)
         (typescript-mode . eglot-ensure))
  :custom (eglot-events-buffer-size . 0)
  :config
  (dolist (item '((my-html-mode . ("vscode-html-language-server" "--stdio"))
                  (vue-mode . (eglot-volar "vue-language-server" "--stdio"))
                  (typescript-mode . ("typescript-language-server" "--stdio"))
                  (java-ts-mode . jdtls-command-contact)))
    (push item eglot-server-programs))
  (add-to-list 'auto-mode-alist '("\\.java\\'" . java-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.yaml\\'" . yaml-ts-mode))
  (advice-add 'eglot-completion-at-point :around #'cape-wrap-buster))
